{{- if and .Values.deployment.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kernelspecs-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.kernelspecsPvc.size }}
  volumeName: kernelspecs-pv
  storageClassName: ""
{{- end }}
